name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: npm test

  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Notify Slack on Success
        if: ${{ needs.build.result == 'success' }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ CI Pipeline succeeded for *${{ github.event.repository.full_name }}*\n> Commit: ${{ github.event.head_commit.url }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on Failure
        if: ${{ needs.build.result == 'failure' }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ CI Pipeline failed for *${{ github.event.repository.full_name }}*\n> Commit: ${{ github.event.head_commit.url }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}