name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: npm test

      - name: Notify Slack
        if: always() 
        run: |
          if [[ "${{ job.status }}" == "success" ]]; then
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ CI Pipeline succeeded for *${{ github.event.repository.full_name }}*\n> Commit: ${{ github.event.head_commit.url }}"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
          elif [[ "${{ job.status }}" == "failure" ]]; then
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ CI Pipeline failed for *${{ github.event.repository.full_name }}*\n> Commit: ${{ github.event.head_commit.url }}"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
          else
            echo "Unexpected status: ${{ job.status }}"
          fi