name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          npm test

      - name: Set Status for Notification
        # Capture job result as output for notification
        id: set-status
        run: echo "status=${{ job.status }}" >> $GITHUB_ENV

  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Notify Slack
        run: |
          if [ "${{ needs.build.result }}" = "success" ]; then
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ CI Pipeline succeeded for *${{ github.event.repository.full_name }}*\n> Commit: ${{ github.event.head_commit.url }}"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
          elif [ "${{ needs.build.result }}" = "failure" ]; then
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ CI Pipeline failed for *${{ github.event.repository.full_name }}*\n> Commit: ${{ github.event.head_commit.url }}"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
          else
            echo "No notification needed."
          fi