name: Run Vitest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Vitest
      - name: Run Vitest tests
        run: npm run test:ci

      # Notify Slack
      - name: Notify Slack
        if: always() # Run this step regardless of the test result
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [[ "${{ job.status }}" == "success" ]]; then
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ Vitest tests passed for *${{ github.event.repository.full_name }}*\n> Commit: ${{ github.event.head_commit.url }}"}' \
            $SLACK_WEBHOOK_URL
          elif [[ "${{ job.status }}" == "failure" ]]; then
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ Vitest tests failed for *${{ github.event.repository.full_name }}*\n> Commit: ${{ github.event.head_commit.url }}"}' \
            $SLACK_WEBHOOK_URL
          else
            echo "Unexpected status: ${{ job.status }}"
          fi