name: Run Vitest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Vitest
      - name: Run Vitest tests
        run: npm run test:ci